### ISSUE TITLE
Question about size of input

### ISSUE THREAD

**Issue by Shaw-Way** [ShqWW/dwconv2d#1]
Hi, author, thanks for sharing the code.
I wonder if the kernel only support input size of 32x32(HxW)

**Comment by ShqWW** [comment]
1. The kernel height and width both support 3~32 and can be unequal.
2. The feature map can be any size as you want (of cource within the GPU memory)
3. I'm not sure the 'input' in your question means the kernel or the feature map, you can run `demo.py` and try different sizes.

**Comment by ShqWW** [comment]
> Hi, author, thanks for sharing the code. I wonder if the kernel only support input size of 32x32(HxW)

1. The kernel height and width both support 3~32 and can be unequal.
2. The feature map can be any size as you want (of cource within the GPU memory)
3. I'm not sure the 'input' in your question means the kernel or the feature map, you can run [test.py](https://github.com/ShqWW/dwconv2d/blob/master/test.py) and try different sizes.

**Comment by Shaw-Way** [comment]
> > Hi, author, thanks for sharing the code. I wonder if the kernel only support input size of 32x32(HxW)
> 
> 1. The kernel height and width both support 3~32 and can be unequal.
> 2. The feature map can be any size as you want (of cource within the GPU memory)
> 3. I'm not sure the 'input' in your question means the kernel or the feature map, you can run [test.py](https://github.com/ShqWW/dwconv2d/blob/master/test.py) and try different sizes.

Thanks for your prompt reply, I mean the size of feature map, have a good day.
